# Generated by Django 4.1.7 on 2023-04-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zodiac_app', '0002_zodiacmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='zodiacmodel',
            name='harakter',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='zodiacmodel',
            name='sides',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='zodiacmodel',
            name='sovmestimost',
            field=models.TextField(blank=True, default=''),
        ),
    ]
